Repository iNavFlight/inav, pull requests merged in 2018-10, with the labels that each got.

#3159 Multirotor braking mode
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/msp/msp_protocol_v2_inav.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
  src/main/target/OMNIBUS/target.h
  src/main/target/common.h
Labels: Experimental

#3879 DSHOT
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/timer_impl_hal.c
  src/main/drivers/timer_impl_stdperiph.c
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/target/COLIBRI_RACE/target.h
  src/main/target/FIREWORKSV2/target.c
  src/main/target/FIREWORKSV2/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/OMNIBUSF7NXT/target.h
  src/main/target/REVO/target.h
Labels: Don't merge, Enhancement, Experimental

#3974 GPS code overhaul (backport)
  make/source.mk
  src/main/build/version.h
  src/main/drivers/gps_i2cnav.c
  src/main/drivers/gps_i2cnav.h
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_i2cnav.c
  src/main/io/gps_naza.c
  src/main/io/gps_nmea.c
  src/main/io/gps_private.h
  src/main/io/gps_ublox.c
  src/main/scheduler/protothreads.h
  src/main/target/OMNIBUS/target.h
  src/main/target/common.h
Labels: BUG, Enhancement
