Repository iNavFlight/inav, pull requests merged in 2018-06, with the labels that each got.

#3314 Remove mid_rc setting
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
  src/main/fc/settings.yaml
  src/main/flight/failsafe.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/servos.c
  src/main/rx/crsf.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus_channels.c
Labels: Cleanup/refactor

#3331 Cleanup of unused functions
  src/main/fc/fc_core.c
  src/main/sensors/rangefinder.c
  src/main/sensors/rangefinder.h
Labels: Cleanup/refactor

#3327 Fix ALTHOLD initial climb when enabled
  src/main/navigation/navigation.c
  src/main/navigation/navigation_private.h
Labels: Enhancement

#3297 Fix and simplify applyFixedWingPitchRollThrottleController()
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
Labels: Cleanup/refactor

#3360 Reset disarm reason at moment of arming
  src/main/fc/fc_core.c
Labels: BUG

#3311 Implement CRUISE MODE for Fixed Wing
  src/main/build/debug.h
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_private.h
  src/main/telemetry/ltm.c
Labels: Enhancement

#3326 Add BB logging of FW navigation PIDs
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Enhancement, Ready to merge

#3382 nav_fw_pitch2thr description adjustment
  docs/Cli.md
Labels: Ready to merge

#3401 Port new VTX API and settings from Betaflight
  docs/Cli.md
  make/source.mk
  src/main/build/debug.h
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_smartaudio.h
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/config/parameter_group_ids.h
  src/main/drivers/serial.h
  src/main/drivers/serial_softserial.c
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/drivers/vtx_rtc6705.c
  src/main/drivers/vtx_rtc6705.h
  src/main/drivers/vtx_rtc6705_soft_spi.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/vtx.c
  src/main/io/vtx.h
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_smartaudio.h
  src/main/io/vtx_string.c
  src/main/io/vtx_string.h
  src/main/io/vtx_tramp.c
  src/main/io/vtx_tramp.h
  src/main/scheduler/scheduler.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/common.h
  src/main/target/common_post.h
  src/utils/rename-ifdefs.py
Labels: Ready to merge
