Repository iNavFlight/inav, pull requests merged in 2018-05, with the labels that each got.

#3119 Remove feature channel forwarding
  docs/Board - Airbot F4 and Flip32 F4.md
  docs/Board - Omnibus F4.md
  docs/Board - Revolution.md
  docs/Channel forwarding.md
  docs/assets/images/mixer_forwarding.png
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/timer.h
  src/main/fc/cli.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/rc_controls.h
  src/main/flight/mixer.h
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/target/ALIENFLIGHTNGF7/target.c
  src/main/target/ANYFCF7/target.c
  src/main/target/FF_FORTINIF4/target.c
  src/main/target/FF_PIKOF4/target.c
  src/main/target/MATEKF405/target.c
  src/main/target/MATEKF405SE/target.c
  src/main/target/MATEKF722/target.c
  src/main/target/RMDO/target.c
  src/main/target/SPRACINGF3/target.c
  src/main/target/SPRACINGF3EVO/target.c
  src/main/target/SPRACINGF3MINI/target.c
  src/main/target/SPRACINGF4EVO/target.c
  src/test/unit/flight_mixer_unittest.cc.txt
Labels: Cleanup, Ready to merge

#3172 gcc 8 support
  src/main/build/atomic.h
  src/main/cms/cms.c
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_types.h
  src/main/config/parameter_group.c
  src/main/config/parameter_group.h
  src/utils/settings.rb
Labels: Experimental

#3188 Forgotten function removed
  src/main/flight/servos.c
  src/test/unit/flight_mixer_unittest.cc.txt
Labels: Cleanup

#3187 Feature SERVO_TILT removed
  docs/Cli.md
  docs/Servo Gimbal.md
  src/main/cms/cms_menu_ledstrip.c
  src/main/config/parameter_group_ids.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.h
  src/main/flight/servos.c
  src/main/io/gimbal.h
  src/main/io/ledstrip.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/test/unit/flight_mixer_unittest.cc.txt
  src/test/unit/serial_msp_unittest.cc.txt
Labels: Cleanup, Ready to merge

#3191 Port of FIR2 second stage gyro filter from Betaflight
  docs/Cli.md
  src/main/build/debug.h
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/fc/settings.yaml
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common.h
Labels: Enhancement, Ready to merge

#3208 Acc notch and gyro stage2 in MSP
  src/main/fc/fc_msp.c
Labels: Enhancement

#2951 Bosch BMI160 gyro support + BrainFPV Radix
  src/main/drivers/accgyro/accgyro_bmi160.c
  src/main/drivers/accgyro/accgyro_bmi160.h
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/RADIX/target.c
  src/main/target/RADIX/target.h
  src/main/target/RADIX/target.mk
Labels: Experimental

#3209 Add probot.stale for automatically managing inactive issues
  .github/stale.yml
Labels: For discussion

#3255 More config properties in Blackbox header
  src/main/blackbox/blackbox.c
Labels: Ready to merge

#3250 GPS altitude can be -ve, so should be SIGNED in blackbox
  src/main/blackbox/blackbox.c
Labels: Ready to merge

#3268 ADC samples averaging with added STM32F30x support
  src/main/drivers/adc.c
  src/main/drivers/adc.h
  src/main/drivers/adc_impl.h
  src/main/drivers/adc_stm32f30x.c
  src/main/drivers/adc_stm32f4xx.c
  src/main/target/common.h
Labels: Enhancement
