Repository iNavFlight/inav, pull requests merged in 2018-03, with the labels that each got.

#2891 Fix timer initialization issues with HAL (F7)
  src/main/drivers/pwm_output.c
  src/main/drivers/timer.h
  src/main/drivers/timer_hal.c
  src/main/drivers/timer_stm32f7xx.c
Labels: Ready to merge

#2846 Bulk gyro/acc reads, temperature sensor framework
  Makefile
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_mpu6000.c
  src/main/drivers/accgyro/accgyro_mpu6050.c
  src/main/drivers/accgyro/accgyro_mpu6500.c
  src/main/drivers/accgyro/accgyro_mpu9250.c
  src/main/drivers/bus.c
  src/main/drivers/bus.h
  src/main/drivers/compass/compass_mpu9250.c
  src/main/fc/fc_tasks.c
  src/main/scheduler/scheduler.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/temperature.c
  src/main/sensors/temperature.h
Labels: Discussion, Enhancement, Ready to merge

#2930 Fix bug in MPU6500 accelerometer detection
  src/main/drivers/accgyro/accgyro_mpu6500.c
Labels: Ready to merge

#2833 Allow aligning the mag to any rotation
  src/main/drivers/compass/compass.h
  src/main/fc/settings.yaml
  src/main/sensors/compass.c
  src/main/sensors/compass.h
Labels: Enhancement
