Repository iNavFlight/inav, pull requests merged in 2018-02, with the labels that each got.

#2691 Debug trace facilities
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/cli.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/io/serial.h
  src/main/main.c
  src/main/sensors/barometer.c
  src/main/sensors/gyro.c
  src/main/target/common.h
Labels: Ready to merge

#2768 Add RC adjustments for board alignment
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
Labels: Testing Required

#2790 Fix hardfault in ledstrip driver due to division by zero
  src/main/io/ledstrip.c
  src/main/target/.common_hardware.c.swp
Labels: Ready to merge

#2835 Revert "SBUS max frame transmission time increased to 6ms."
  src/main/rx/sbus.c
Labels: Bug
