Repository iNavFlight/inav, pull requests merged in 2018-11, with the labels that each got.

#3725 Initial support for Benewake TF-Mini lidar
  make/source.mk
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/rangefinder.h
  src/main/io/rangefinder_benewake.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/msp/msp_protocol_v2_common.h
  src/main/sensors/rangefinder.c
  src/main/sensors/rangefinder.h
  src/main/target/REVO/target.h
  src/main/target/common.h
Labels: In progress, Testing Required

#3984 SPI/SDCARD refactoring
  make/source.mk
  src/main/drivers/bus.c
  src/main/drivers/bus.h
  src/main/drivers/bus_busdev_spi.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/dma.h
  src/main/drivers/dma_stm32f3xx.c
  src/main/drivers/dma_stm32f4xx.c
  src/main/drivers/dma_stm32f7xx.c
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_spi.c
  src/main/fc/fc_init.c
  src/main/io/asyncfatfs/asyncfatfs.c
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/BLUEJAYF4/target.h
  src/main/target/F4BY/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/FURYF3/target.h
  src/main/target/KAKUTEF7/target.h
  src/main/target/KROOZX/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF405SE/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKF722SE/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/RADIX/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/YUPIF4/target.h
  src/main/target/common_hardware.c
Labels: Don't merge, Testing Required

#4021 Fix non-working PPM; Enable PPM on OMNIBUSF7 NXT
  src/main/drivers/rx_pwm.c
  src/main/rx/pwm.c
  src/main/target/OMNIBUSF7NXT/target.c
Labels: Ready to merge

#4026 NXT OSD fixes
  src/main/target/OMNIBUSF7NXT/target.h
Labels: Ready to merge

#4046 Fix PPM input initialization
  src/main/drivers/rx_pwm.c
Labels: BUG
