Repository iNavFlight/inav, pull requests merged in 2018-04, with the labels that each got.

#3038 Minor debug cleanup
  src/main/navigation/navigation_multicopter.c
Labels: Cleanup

#2978 Mixer refactoring - make FC unaware of anything besides mixer rules
  docs/Cli.md
  docs/Mixer.md
  src/main/blackbox/blackbox.c
  src/main/config/config_master.h
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/pwm_output.c
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/msp/msp_protocol.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/target/COLIBRI/config.c
  src/main/target/CRAZEPONYMINI/target.h_
  src/main/target/FALCORE/config.c
  src/main/target/FF_F35_LIGHTNING/config.c
  src/main/target/KFC32F3_INAV/target.h
  src/main/target/MATEKF405SE/config.c
  src/main/target/PIKOBLX/target.h
  src/main/target/common.h
  src/main/telemetry/mavlink.c
  src/test/unit/target.h
Labels: Enhancement, Ready to merge

#3085 Update version to 2.0
  src/main/build/version.h
Labels: Ready to merge

#2893 MC PID improvements
  docs/Cli.md
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/target/FALCORE/config.c
Labels: Enhancement, Ready to merge

#3104 Reset Iterm after autotrim is done
  src/main/flight/servos.c
Labels: Enhancement

#3106 Naze and all it traces removed
  build_docs.sh
  docs/1wire.md
  docs/Battery.md
  docs/Blackbox.md
  docs/Board - AlienFlight.md
  docs/Board - CC3D.md
  docs/Board - Naze32.md
  docs/Board - Paris Air Hero 32 F3.md
  docs/Board - Paris Air Hero 32.md
  docs/Board - RMDO.md
  docs/Board - Sparky.md
  docs/Boards.md
  docs/Buzzer.md
  docs/Display.md
  docs/LedStrip.md
  docs/Oneshot.md
  docs/Rx.md
  docs/Serial.md
  docs/Sonar.md
  docs/Spektrum bind.md
  docs/development/Building in Mac OS X.md
  docs/development/Building in Windows light.md
  docs/development/Building in Windows.md
  docs/development/Hardware Debugging in Eclipse.md
  docs/development/Hardware Debugging.md
  fake_travis_build.sh
  src/main/drivers/accgyro/accgyro_mma845x.c
  src/main/drivers/compass/compass_hmc5883l.c
  src/main/drivers/io_pca9685.c
  src/main/fc/config.c
  src/main/fc/fc_init.c
  src/main/sensors/acceleration.c
  src/main/sensors/compass.c
  src/main/target/ALIENFLIGHTF3/AlienFlight.md
  src/main/target/ALIENFLIGHTF4/AlienFlight.md
  src/main/target/ALIENFLIGHTNGF7/AlienFlight.md
  src/main/target/NAZE/AIRHERO32.mk_
  src/main/target/NAZE/hardware_revision.c
  src/main/target/NAZE/hardware_revision.h
  src/main/target/NAZE/target.c
  src/main/target/NAZE/target.h_
  src/main/target/NAZE/target.mk_
Labels: Cleanup

#3105 Minor cleanup of unused or legacy defines
  src/main/fc/cli.c
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/io/beeper.c
  src/main/io/displayport_msp.c
  src/main/msp/msp_serial.c
  src/main/target/PIKOBLX/target.h
  src/main/target/common.h
Labels: Cleanup

#3109 STM32F1 removed from sourcecode
  docs/Boards.md
  src/main/config/config_streamer.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/dma.c
  src/main/drivers/exti.c
  src/main/drivers/gpio.h
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/light_ws2811strip_stdperiph.c
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_output.c
  src/main/drivers/rangefinder/rangefinder_hcsr04.c
  src/main/drivers/rcc.c
  src/main/drivers/rx_spi.c
  src/main/drivers/serial_softserial.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/fc/config.c
  src/main/fc/fc_init.c
  src/main/msp/msp_serial.h
  src/main/platform.h
  src/main/target/ALIENFLIGHTF3/AlienFlight.md
  src/main/target/ALIENFLIGHTF4/AlienFlight.md
  src/main/target/ALIENFLIGHTNGF7/AlienFlight.md
  src/main/target/common.h
  src/main/vcp/hw_config.c
  src/main/vcp/hw_config.h
  src/main/vcp/platform_config.h
Labels: Review needed, Testing Required

#3117 I2C Rangefinders enabled on Matek F722
  src/main/target/MATEKF722/target.h
Labels: Enhancement

#3118 Configurable switch-disarm delay
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
  src/main/fc/settings.yaml
  src/main/flight/failsafe.c
  src/main/navigation/navigation.c
Labels: Enhancement, Ready to merge

#3121 RANGEFINDER_HCSR04_PWM_TRIGGER_PIN removed
  src/main/sensors/rangefinder.c
Labels: Cleanup

#2955 Add support for multiple OSD layouts
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/cms/cms_types.h
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/target/common.h
Labels: Enhancement
