Repository iNavFlight/inav, pull requests merged in 2018-12, with the labels that each got.

#4023 Limit Iterm on FW depending on stick position
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Don't merge, Experimental

#4050 Make the debug array cells int32 and increase cell count to 8
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/fc_msp.c
  src/main/msp/msp_protocol_v2_inav.h
  src/test/unit/flight_failsafe_unittest.cc.txt
  src/test/unit/flight_imu_unittest.cc.txt
  src/test/unit/flight_mixer_unittest.cc.txt
  src/test/unit/navigation_unittest.cc.txt
  src/test/unit/serial_msp_unittest.cc.txt
  src/test/unit/telemetry_hott_unittest.cc
Labels: Ready to merge

#4064 Add option to switch to layout #0 during failsafe
  docs/Cli.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Ready to merge

#4056 Fix OMNIBUSF7NXT DSHOT DMA allocation for M6
  src/main/target/OMNIBUSF7NXT/target.c
Labels: Don't merge

#4104 [MATEKF722SE] Fix beeper; Enable LEDSTRIP
  src/main/target/MATEKF722SE/target.h
Labels: BUG

#4111 Enable DSHOT on OmnibusF4 and ASGARD boards
  src/main/target/ASGARD32F4/target.c
  src/main/target/ASGARD32F4/target.h
  src/main/target/ASGARD32F7/target.c
  src/main/target/ASGARD32F7/target.h
  src/main/target/OMNIBUSF4/target.h
Labels: Testing Required
