Repository iNavFlight/inav, pull requests merged in 2019-06, with the labels that each got.

#4448 Smarter RoC/RoD acceleration limit
  src/main/navigation/navigation_multicopter.c
Labels: Don't merge, In progress

#4786 Add vario sensor to CRSF telemetry
  src/main/rx/crsf.h
  src/main/telemetry/crsf.c
Labels: Feature request

#4807 Fix OSD_DEBUG
  src/main/io/osd.c
Labels: Don't merge, Testing Required

#4837 Fix CRSF vario
  src/main/telemetry/crsf.c
Labels: Ready to merge
