Repository iNavFlight/inav, pull requests merged in 2019-03, with the labels that each got.

#4431 Fix missing owner names
  src/main/drivers/resource.c
Labels: BUG

#4420 Enforce board alignment setting limits in updateBoardAlignment()
  src/main/sensors/boardalignment.c
Labels: BUG

#4144 Logic Conditions framework
  make/source.mk
  src/main/common/logic_condition.c
  src/main/common/logic_condition.h
  src/main/config/parameter_group_ids.h
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/scheduler/scheduler.h
  src/main/target/common.h
Labels: Enhancement

#4467 Refactor motor mixer to prepare for primary and secondary mixer bank
  src/main/build/build_config.h
  src/main/fc/cli.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/runtime_config.h
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/target/ALIENFLIGHTF3/config.c
  src/main/target/ALIENFLIGHTF4/config.c
  src/main/target/ALIENFLIGHTNGF7/config.c
  src/main/target/SPRACINGF3NEO/target.h
  src/test/unit/platform.h
Labels: Cleanup/refactor

#4326 Convert XY VEL TO ACC controller to use feed forward component
  src/main/blackbox/blackbox.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_private.h
Labels: Enhancement

#4482 Move FW PID FF component to dedicated config structure
  src/main/fc/settings.yaml
  src/main/flight/pid.c
Labels: Cleanup/refactor

#4484 Remove PosHold support settings from PID bank
  docs/Cli.md
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Cleanup/refactor

#4475 Make Dterm FIR filter configurable
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Feedback required

#4447 Fix BETAFLIGHTF4 target motor 1
  src/main/target/BETAFLIGHTF4/target.c
Labels: BUG

#4494 Fix MC servo mapping on AnyFCF7
  src/main/target/ANYFCF7/target.c
Labels: BUG

#4499 Set default home reset to first arm
  src/main/navigation/navigation_pos_estimator.c
Labels: Feedback required

#4501 Servo output logging in blackbox
  src/main/blackbox/blackbox.c
Labels: Enhancement

#4483 Second iteration of making F7 fast
  src/main/blackbox/blackbox.c
  src/main/fc/fc_core.c
  src/main/fc/runtime_config.c
  src/main/flight/pid.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fw_launch.c
  src/main/navigation/navigation_pos_estimator.c
  src/main/scheduler/scheduler.c
Labels: Enhancement

#4403 Make VelXY Dterm LPF user configurable
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Enhancement, Experimental

#4544 Add softserial on UART2 for WINGFC/FF_F35 targets
  src/main/target/FF_F35_LIGHTNING/target.c
  src/main/target/FF_F35_LIGHTNING/target.h
  src/main/target/FF_F35_LIGHTNING/target.mk
Labels: Feature request, Ready to merge

#4529 Allow configurable DMA memory buffer element sizes
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/pwm_output.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/drivers/timer_impl.h
  src/main/drivers/timer_impl_hal.c
  src/main/drivers/timer_impl_stdperiph.c
Labels: Testing Required
