Repository iNavFlight/inav, pull requests merged in 2019-01, with the labels that each got.

#4145 smix reverse removed
  docs/Mixer.md
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/flight/servos.c
  src/main/flight/servos.h
Labels: Cleanup/refactor

#4147 Implement support for FFPV 2.4GHz VTX protocol
  make/source.mk
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_vtx_ffpv.c
  src/main/cms/cms_menu_vtx_ffpv.h
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/serial.h
  src/main/io/vtx.c
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
  src/main/io/vtx_ffpv24g.c
  src/main/io/vtx_ffpv24g.h
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_string.c
  src/main/io/vtx_tramp.c
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/common.h
Labels: Don't merge, In progress

#4161 Enable Feature Airmode by default
  src/main/fc/config.c
  src/main/target/BEEROTORF4/target.h
  src/main/target/FALCORE/config.c
Labels: Enhancement

#3789 IMU orientation sanity check improvements
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
  src/main/flight/imu.c
Labels: Experimental

#3977 Pitot sensor fixes and improvements
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/drivers/bus_i2c_stm32f40x.c
  src/main/drivers/pitotmeter.h
  src/main/drivers/pitotmeter_adc.c
  src/main/drivers/pitotmeter_ms4525.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.h
  src/main/navigation/navigation_pos_estimator.c
  src/main/scheduler/protothreads.h
  src/main/sensors/pitotmeter.c
  src/main/sensors/pitotmeter.h
  src/main/target/REVO/target.c
  src/main/target/REVO/target.h
  src/main/target/REVO/target.mk
  src/main/target/common_hardware.c
Labels: Enhancement

#3740 Experimental biquad RC fitler instead of RC interpolation
  docs/Cli.md
  make/source.mk
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/fc/fc_core.c
  src/main/fc/rc_smoothing.c
  src/main/fc/rc_smoothing.h
  src/main/fc/settings.yaml
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/common.h
Labels: Enhancement

#4196 Fix non-working AGL estimation
  src/main/common/filter.c
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_pos_estimator_agl.c
  src/main/navigation/navigation_pos_estimator_private.h
Labels: BUG

#4221 DSHOT enabled on AirbotF4
  src/main/target/AIRBOTF4/target.h
Labels: Enhancement
