Repository iNavFlight/inav, pull requests merged in 2019-05, with the labels that each got.

#3795 Optic flow & surface improvements
  src/main/fc/cli.c
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/msp/msp_protocol_v2_inav.h
  src/main/navigation/navigation_pos_estimator_flow.c
  src/main/scheduler/scheduler.h
  src/main/sensors/diagnostics.c
  src/main/sensors/initialisation.c
  src/main/sensors/opflow.c
  src/main/sensors/opflow.h
  src/main/target/FURYF4OSD/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/RADIX/target.h
  src/main/target/REVO/target.h
  src/main/target/SPARKY2/target.h
Labels: Enhancement, Ready to merge

#4702 Switch back to 32-bit DMA on F4
  src/main/drivers/timer_def_stm32f4xx.h
Labels: Ready to merge

#4696 g-force OSD item and stats
  docs/Cli.md
  src/main/cms/cms_menu_osd.c
  src/main/fc/fc_core.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
Labels: Feature request

#4652 OSD : icon / value / unit re-ordering
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
Labels: Ready to merge

#4705 Refactor pwm motor/servo output to be mixer-driven
  make/source.mk
  src/main/drivers/1-wire.c
  src/main/drivers/compass/compass_hmc5883l.c
  src/main/drivers/logging.c
  src/main/drivers/logging.h
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/rangefinder/rangefinder_hcsr04.c
  src/main/drivers/rx_pwm.c
  src/main/drivers/rx_pwm.h
  src/main/drivers/serial.h
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/io/osd.c
  src/main/io/serial_4way.c
  src/main/rx/pwm.c
  src/main/rx/pwm.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/sensors/acceleration.c
  src/main/sensors/barometer.c
  src/main/sensors/compass.c
  src/main/sensors/gyro.c
  src/main/sensors/initialisation.c
  src/main/sensors/opflow.c
  src/main/sensors/pitotmeter.c
  src/main/sensors/rangefinder.c
  src/main/sensors/temperature.c
  src/main/target/ALIENFLIGHTF3/config.c
  src/main/target/ALIENFLIGHTF4/config.c
  src/main/target/ALIENFLIGHTNGF7/config.c
  src/main/target/ASGARD32F4/config.c
  src/main/target/ASGARD32F7/config.c
  src/main/target/FALCORE/config.c
  src/main/target/REVO/target.h
  src/main/target/STM32F3DISCOVERY/target.c
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/STM32F3DISCOVERY/target.mk
  src/main/target/common.h
  src/test/unit/sensor_gyro_unittest.cc
Labels: Ready to merge

#4704 MSP override feature
  make/source.mk
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_osd.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/rx/msp_override.c
  src/main/rx/msp_override.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/common.h
Labels: Feature request

#4558 OSD Hud + LoRa radar (nearby aircrafts)
  make/source.mk
  src/main/cms/cms_menu_osd.c
  src/main/common/constants.h
  src/main/drivers/osd_symbols.h
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_hud.c
  src/main/io/osd_hud.h
  src/main/msp/msp_protocol_v2_common.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Enhancement

#4741 Make MAVlink telemetry stream rates configurable
  src/main/fc/settings.yaml
  src/main/telemetry/mavlink.c
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
Labels: Feature request

#4754 Add MATEKF411 target with one full duplex softserial: MATEKF411_FD_SFTSRL
  make/release.mk
  src/main/target/MATEKF411/MATEKF411_FD_SFTSRL.mk
  src/main/target/MATEKF411/target.h
Labels: Feature request
