Repository iNavFlight/inav, pull requests merged in 2019-02, with the labels that each got.

#4275 Added ITCM-RAM loading
  src/main/startup/startup_stm32f722xx.s
  src/main/target/system_stm32f7xx.c
Labels: In progress, Testing Required

#4202 Refactor run-time calibration
  make/source.mk
  src/main/common/calibration.c
  src/main/common/calibration.h
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/rc_controls.c
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_pos_estimator_private.h
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/barometer.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/pitotmeter.c
  src/main/sensors/pitotmeter.h
  src/main/sensors/sensors.h
  src/test/Makefile
  src/test/unit/maths_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
Labels: BUG, Enhancement, Testing Required

#4302 increase blackbox denom range (cleanup)
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/msp/msp_protocol.h
  src/main/msp/msp_protocol_v2_inav.h
Labels: Feedback required

#4407 New temperature related OSD features + bugfix
  docs/Temperature sensors.md
  src/main/drivers/max7456_symbols.h
  src/main/fc/cli.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/sensors/temperature.c
  src/main/sensors/temperature.h
Labels: BUG, Feature request

#4162 State HELICOPTER removed
  src/main/fc/runtime_config.h
  src/main/flight/mixer.c
Labels: Cleanup/refactor

#4148 New mixer inputs for stabilized axises
  docs/Mixer.md
  src/main/flight/servos.c
  src/main/flight/servos.h
Labels: Enhancement
