Repository iNavFlight/inav, pull requests merged in 2019-04, with the labels that each got.

#4602 Enable servos in MR mode on Kakute F7
  src/main/target/KAKUTEF7/target.c
Labels: Testing Required

#4592 Lazy SPI bus init
  src/main/drivers/bus.c
  src/main/drivers/bus.h
  src/main/drivers/bus_busdev_spi.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/sdcard.c
  src/main/fc/fc_init.c
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/BLUEJAYF4/target.h
  src/main/target/F4BY/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/FURYF3/target.h
  src/main/target/FURYF4OSD/target.h
  src/main/target/KAKUTEF7/target.h
  src/main/target/KROOZX/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF405SE/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKF722SE/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/YUPIF4/target.h
Labels: Testing Required

#4644 Fix timer DMA on F7
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/pwm_output.c
  src/main/drivers/timer_def_stm32f3xx.h
  src/main/drivers/timer_def_stm32f4xx.h
  src/main/drivers/timer_def_stm32f7xx.h
Labels: BUG

#4634 On MR allow airmode to be sticky and activated by throttle threshold
  src/main/fc/fc_core.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/io/osd.c
  src/main/telemetry/crsf.c
  src/test/unit/flight_failsafe_unittest.cc.txt
Labels: In progress
