Repository iNavFlight/inav, pull requests merged in 2019-11, with the labels that each got.

#5187 Baro fix SPI, probably blackbox, PPM on all targets SS, orientation issue in some targets and other minor changes in OmnibusF4
  src/main/target/OMNIBUSF4/target.c
  src/main/target/OMNIBUSF4/target.h
Labels: Testing Required

#5181 Cleanup debugs and USE_ defines that are always on
  src/main/build/debug.h
  src/main/fc/config.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/flight/gyroanalyse.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation_multicopter.c
  src/main/sensors/acceleration.c
  src/main/sensors/gyro.c
  src/main/target/common.h
Labels: Enhancement

#5129 PID/PIFF refactoring
  src/main/common/maths.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/target/OMNIBUS/target.h
Labels: Cleanup/refactor
