Repository iNavFlight/inav, pull requests merged in 2020-08, with the labels that each got.

#6009 Fix frequency calculation for RPM filter
  src/main/flight/rpm_filter.c
Labels: BUG

#6006 Drop gyro method of ITerm relax
  src/main/build/debug.h
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Release Notes

#5991 [TARGETS] Add SPEEDYBEEF7
  src/main/target/SPEEDYBEEF7/config.c
  src/main/target/SPEEDYBEEF7/target.c
  src/main/target/SPEEDYBEEF7/target.h
  src/main/target/SPEEDYBEEF7/target.mk
Labels: Release Notes

#6029 Set OneShot125 as a default ESC protocol
  src/main/flight/mixer.c
Labels: Release Notes

#5454 Simplify RX config for standard receiver setups
  src/main/rx/fport.c
Labels: Release Notes

#6032 [RX] Make halfDuplex (exposed as serialrx_halfduplex) a tristate
  docs/Rx.md
  docs/Settings.md
  src/main/common/tristate.h
  src/main/fc/settings.yaml
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/sumd.c
  src/main/rx/xbus.c
  src/main/target/FF_FORTINIF4/config.c
  src/main/target/FF_PIKOF4/config.c
Labels: Release Notes

#5918 Add target for FrSky's ROVERF7 FC
  make/release.mk
  make/targets.mk
  src/main/target/FRSKY_ROVERF7/target.c
  src/main/target/FRSKY_ROVERF7/target.h
  src/main/target/FRSKY_ROVERF7/target.mk
Labels: Release Notes

#5962 Take into account video aspect ratio when drawing AHI
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_grid.c
Labels: Release Notes

#6041 [OSD] Fix default value for osd_sidebar_horizontal_offset
  src/main/io/osd.c
Labels: BUG

#4446 Calibration for MAG gain
  make/release.mk
  make/targets.mk
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/target/KFC32F3_INAV/target.mk_
Labels: Enhancement, Ready to merge, Release Notes

#6040 [RTH Estimator] Fix display condition
  src/main/flight/rth_estimator.c
Labels: BUG, Release Notes
