Repository iNavFlight/inav, pull requests merged in 2020-12, with the labels that each got.

#6366 Revert "Adds DJI OSD support to 2x F3 boards"
  src/main/target/AIRHEROF3/target.h
  src/main/target/SPRACINGF3/target.h
Labels: BUG

#6357 Cleanup unused SPI receivers
  src/main/CMakeLists.txt
  src/main/drivers/rx_nrf24l01.c
  src/main/drivers/rx_nrf24l01.h
  src/main/drivers/rx_xn297.c
  src/main/drivers/rx_xn297.h
  src/main/fc/settings.yaml
  src/main/rx/nrf24_cx10.c
  src/main/rx/nrf24_cx10.h
  src/main/rx/nrf24_h8_3d.c
  src/main/rx/nrf24_h8_3d.h
  src/main/rx/nrf24_inav.c
  src/main/rx/nrf24_inav.h
  src/main/rx/nrf24_syma.c
  src/main/rx/nrf24_syma.h
  src/main/rx/nrf24_v202.c
  src/main/rx/nrf24_v202.h
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
  src/main/target/OMNIBUS/target.h
Labels: Cleanup/refactor

#6333 Add safehome_max_distance option. Choose nearest safehome.
  docs/Safehomes.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Enhancement

#6420 add MSP for setting and getting safe homes
  src/main/fc/fc_msp.c
  src/main/msp/msp_protocol_v2_inav.h
Labels: Enhancement

#6431 update EGNOS PRN mask to latest EGSA definition, fix SBAS for non-Galileo usage.
  src/main/io/gps_ublox.c
Labels: Release Notes
