Repository iNavFlight/inav, pull requests merged in 2020-11, with the labels that each got.

#6090 Add additional MSP-based sensors
  src/main/CMakeLists.txt
  src/main/drivers/barometer/barometer_msp.c
  src/main/drivers/barometer/barometer_msp.h
  src/main/drivers/compass/compass_msp.c
  src/main/drivers/compass/compass_msp.h
  src/main/drivers/pitotmeter/pitotmeter.h
  src/main/drivers/pitotmeter/pitotmeter_adc.c
  src/main/drivers/pitotmeter/pitotmeter_adc.h
  src/main/drivers/pitotmeter/pitotmeter_fake.c
  src/main/drivers/pitotmeter/pitotmeter_fake.h
  src/main/drivers/pitotmeter/pitotmeter_ms4525.c
  src/main/drivers/pitotmeter/pitotmeter_ms4525.h
  src/main/drivers/pitotmeter/pitotmeter_msp.c
  src/main/drivers/pitotmeter/pitotmeter_msp.h
  src/main/drivers/pitotmeter/pitotmeter_virtual.c
  src/main/drivers/pitotmeter/pitotmeter_virtual.h
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_msp.c
  src/main/io/gps_private.h
  src/main/io/opflow_msp.c
  src/main/io/rangefinder_msp.c
  src/main/msp/msp_protocol_v2_sensor.h
  src/main/msp/msp_protocol_v2_sensor_msg.h
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/sensors/pitotmeter.c
  src/main/sensors/pitotmeter.h
  src/main/target/common.h
  src/main/target/common_post.h
Labels: Release Notes

#6269 [GPS] Support for M9N module and other u-blox 9 receivers
  src/main/io/gps_ublox.c
Labels: Ready to merge, Release Notes

#6086 Return GCS waypoint in the case of waypoint 255 when GCS assist enabled
  src/main/navigation/navigation.c
Labels: Ready to merge

#6067 Make nav_overrides_motor_stop tristate: OFF | AUTO_ONLY | ALL_NAV
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Feature request, Release Notes

#6319 [LAUNCH] Fix a bug with throttling up in launch mode before throttle is raised
  src/main/navigation/navigation_fw_launch.c
Labels: Release Notes
