Repository iNavFlight/inav, pull requests merged in 2020-09, with the labels that each got.

#6087 [GYRO] Fix ICM20689 driver not switching to fast SPI speed
  src/main/drivers/accgyro/accgyro_icm20689.c
Labels: BUG

#6108 New functions: sin, cos, tan and range scaling
  docs/Programming Framework.md
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Release Notes

#6137 Ability to read current waypoint index as part of LC
  docs/Programming Framework.md
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Release Notes

#6138 First cut on KakuteF7 Mini V3
  src/main/target/KAKUTEF7MINIV3/CMakeLists.txt
  src/main/target/KAKUTEF7MINIV3/target.c
  src/main/target/KAKUTEF7MINIV3/target.h
Labels: Ready to merge
