Repository iNavFlight/inav, pull requests merged in 2020-10, with the labels that each got.

#6182 [GPS] Support GPS baud 230400
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_nmea.c
  src/main/io/gps_ublox.c
Labels: BUG

#6195 Inav osd gvar
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Ready to merge

#6101 TURN_ASSIST pitch gain for coordinated turns
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Don't merge, For discussion
