Repository iNavFlight/inav, pull requests merged in 2020-05, with the labels that each got.

#5645 Apply Dterm filters on derivative, not error
  src/main/flight/pid.c
Labels: Testing Required

#5608 [DJI] Don't show DJI OSD items if they don't have a dependency feature enabled
  src/main/config/feature.c
  src/main/io/osd_dji_hd.c
Labels: BUG, Testing Required

#5654 cli: aux command print permamentId
  src/main/fc/cli.c
Labels: Rebase Required

#5655 Adjustable control smoothness for fixed wing navigation
  docs/Cli.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_private.h
Labels: Enhancement, Ready to merge

#5674 [ESC_SENSOR] Add listen_only mode
  src/main/drivers/pwm_output.c
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/settings.yaml
  src/main/sensors/esc_sensor.c
  src/main/sensors/esc_sensor.h
Labels: Testing Required

#5651 Output servos as SBUS stream
  docs/Cli.md
  make/source.mk
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/pwm_output.c
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/io/pwmdriver_i2c.c
  src/main/io/serial.h
  src/main/io/servo_sbus.c
  src/main/io/servo_sbus.h
  src/main/rx/sbus.c
  src/main/rx/sbus_channels.c
  src/main/rx/sbus_channels.h
  src/main/target/common.h
Labels: Ready to merge

#5691 Fix OSD hang due to compiler optimization bug
  src/main/drivers/max7456.c
Labels: BUG
