Repository iNavFlight/inav, pull requests merged in 2020-04, with the labels that each got.

#5609 On rovers and boats stop motors when mission is done
  src/main/navigation/navigation.c
  src/main/navigation/navigation_private.h
  src/main/navigation/navigation_rover_boat.c
Labels: Ready to merge

#5446 Add a F.Port section to the RX documentation
  docs/Rx.md
Labels: In progress, Inactive

#5615 [GYRO] Refactor gyro driver for dual-gyro support
  src/main/sensors/diagnostics.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/test/unit/sensor_gyro_unittest.cc
Labels: Cleanup/refactor, Ready to merge

#5641 Fix CRC algo for FrSky S.Port and F.Port
  make/source.mk
  src/main/rx/fport.c
  src/main/rx/frsky_crc.c
  src/main/rx/frsky_crc.h
  src/main/telemetry/smartport.c
Labels: Testing Required
