Repository iNavFlight/inav, pull requests merged in 2020-03, with the labels that each got.

#5255 Initial cut for NAV yaw adjustments with separate PID controller on FW
  src/main/build/debug.h
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
Labels: In progress

#5490 Revisit FAST_RAM usages
  src/main/common/maths.c
  src/main/config/feature.c
  src/main/fc/runtime_config.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/servos.c
  src/main/navigation/navigation_fw_launch.c
  src/main/navigation/navigation_pos_estimator.c
Labels: Enhancement

#5494 Bump osdConfig PG version
  src/main/io/osd.c
Labels: BUG

#5489 Allow some files to be compiled with -O2 instead of -Os
  Makefile
  make/source.mk
  src/main/common/typeconversion.c
  src/main/io/dashboard.c
  src/main/io/dashboard.h
  src/main/target/common_post.h
Labels: Enhancement

#5501 Dzikuvx fastram rewise part 2
  src/main/common/encoding.c
  src/main/common/filter.c
  src/main/common/global_functions.c
  src/main/common/maths.c
  src/main/common/typeconversion.c
  src/main/drivers/max7456.c
  src/main/drivers/pwm_output.c
  src/main/fc/fc_core.c
  src/main/flight/gyroanalyse.c
  src/main/flight/imu.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/rpm_filter.c
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/sbus.c
  src/main/scheduler/scheduler.c
  src/main/sensors/acceleration.c
  src/main/sensors/boardalignment.c
  src/main/sensors/esc_sensor.c
  src/main/sensors/gyro.c
  src/main/telemetry/crsf.c
  src/main/telemetry/smartport.c
  src/test/unit/platform.h
Labels: Enhancement

#5513 Document telemetry sensor 0x450
  docs/Telemetry.md
Labels: Ready to merge

#5557 Refactor NVIC; Fix ATOMIC_BLOCK not being actually atomic
  src/main/build/atomic.h
  src/main/drivers/bus_i2c_hal.c
  src/main/drivers/dma_stm32f3xx.c
  src/main/drivers/dma_stm32f4xx.c
  src/main/drivers/dma_stm32f7xx.c
  src/main/drivers/exti.c
  src/main/drivers/nvic.h
  src/main/drivers/sdcard/sdmmc_sdio_f4xx.c
  src/main/drivers/sdcard/sdmmc_sdio_f7xx.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/timer_impl_hal.c
  src/main/drivers/timer_impl_stdperiph.c
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/telemetry/crsf.c
  src/main/vcp/hw_config.c
  src/main/vcpf4/usb_bsp.c
Labels: BUG, Cleanup/refactor
