Repository iNavFlight/inav, pull requests merged in 2020-06, with the labels that each got.

#5737 Fix ESC_SERIAL crash
  src/main/sensors/esc_sensor.c
Labels: Ready to merge

#5757 Added functions to retrieve the UART Idle state (Needed for Spektrum SRXL2 support)
  src/main/drivers/serial.c
  src/main/drivers/serial.h
  src/main/drivers/serial_softserial.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_usb_vcp.c
Labels: Ready to merge

#5825 Esc telemetry fix
  src/main/fc/fc_init.c
Labels: BUG, Release Notes

#5642 Add setpoint derivative feed forward term to PID controller
  docs/Board - OMNIBUS.md
  docs/Cli.md
  make/release.mk
  make/targets.mk
  src/main/blackbox/blackbox.c
  src/main/build/debug.h
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/fc/config.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/io/osd_dji_hd.c
  src/main/target/FALCORE/config.c
  src/main/target/OMNIBUS/target.mk_
Labels: Enhancement, Release Notes

#5823 [VTX] Always process VTX driver updates, regardless of arming state
  src/main/io/vtx.c
Labels: Release Notes

#5519 Gyro Kalman filter from EmuFlight
  make/source.mk
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/flight/kalman.c
  src/main/flight/kalman.h
  src/main/flight/pid.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common.h
Labels: Experimental

#5845 [VTX] Allow override of max power capability for buggy VTXes
  docs/Cli.md
  src/main/fc/settings.yaml
  src/main/io/vtx.c
  src/main/io/vtx.h
  src/main/io/vtx_tramp.c
Labels: CLI, Release Notes

#5851 support SET_HEAD and SET_POI
  docs/Navigation.md
  src/main/fc/cli.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes

#5862 [BARO] Add DPS310 barometer driver; enable on some targets
  src/main/drivers/barometer/barometer_dps310.c
  src/main/drivers/barometer/barometer_dps310.h
  src/main/drivers/bus.h
  src/main/fc/settings.yaml
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/target/FURYF4OSD/target.h
  src/main/target/FURYF4OSD/target.mk
  src/main/target/IFLIGHTF4_TWING/target.h
  src/main/target/IFLIGHTF4_TWING/target.mk
  src/main/target/IFLIGHTF7_TWING/target.h
  src/main/target/IFLIGHTF7_TWING/target.mk
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF405/target.mk
  src/main/target/MATEKF405SE/target.h
  src/main/target/MATEKF405SE/target.mk
  src/main/target/MATEKF411/target.h
  src/main/target/MATEKF411/target.mk
  src/main/target/MATEKF411SE/target.h
  src/main/target/MATEKF411SE/target.mk
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKF722/target.mk
  src/main/target/MATEKF722PX/target.h
  src/main/target/MATEKF722PX/target.mk
  src/main/target/MATEKF722SE/target.h
  src/main/target/MATEKF722SE/target.mk
  src/main/target/MATEKF765/target.h
  src/main/target/MATEKF765/target.mk
  src/main/target/common_hardware.c
Labels: Ready to merge, Release Notes

#5758 [Target] Add IFLIGHT_SucceX_D board support.
  src/main/target/IFLIGHT_SucceX_D/target.c
  src/main/target/IFLIGHT_SucceX_D/target.h
  src/main/target/IFLIGHT_SucceX_D/target.mk
Labels: Feature request, In progress

#5886 Add IFLIGHT_SucceX_D board support
  make/release.mk
  src/main/target/IFLIGHTF4_SUCCEXD/target.c
  src/main/target/IFLIGHTF4_SUCCEXD/target.h
  src/main/target/IFLIGHTF4_SUCCEXD/target.mk
Labels: Release Notes
