Repository iNavFlight/inav, pull requests merged in 2020-07, with the labels that each got.

#5912 Target PIKOBLX: Remove pin conflict between non existent current adc pin and pwm6
  src/main/target/PIKOBLX/target.h
Labels: Release Notes

#5711 Remove Air from OSD mode display
  src/main/io/osd.c
Labels: Enhancement, Release Notes

#5906 Add Azimuth OSD element
  src/main/cms/cms_menu_osd.c
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Enhancement, Release Notes

#5950 [MAVLINK] Update flight modes map to match Arduplane/Arducopter
  src/main/telemetry/mavlink.c
Labels: Release Notes

#5934 Set OSD Layout with global functions
  docs/Global Functions.md
  src/main/io/osd.c
  src/main/programming/global_functions.c
  src/main/programming/global_functions.h
Labels: Ready to merge

#5338 Attenuate VEL_XY when UAV is traveling at high speed
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Enhancement, Release Notes

#5956 First cut of HGLRC Zeus F722
  make/release.mk
  src/main/target/HGLRCF722/config.c
  src/main/target/HGLRCF722/target.c
  src/main/target/HGLRCF722/target.h
  src/main/target/HGLRCF722/target.mk
Labels: Release Notes

#5959 I/O Expander Board Support
  docs/Logic Conditions.md
  make/source.mk
  src/main/build/debug.h
  src/main/drivers/bus.h
  src/main/drivers/io_pcf8574.c
  src/main/drivers/io_pcf8574.h
  src/main/drivers/io_port_expander.c
  src/main/drivers/io_port_expander.h
  src/main/fc/fc_init.c
  src/main/fc/settings.yaml
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
  src/main/target/common.h
  src/main/target/common_hardware.c
Labels: Release Notes

#5857 Add support for FrSkyOSD version 2
  make/source.mk
  src/main/cms/cms.c
  src/main/cms/cms_menu_osd.c
  src/main/config/parameter_group_ids.h
  src/main/drivers/display_canvas.c
  src/main/drivers/display_canvas.h
  src/main/drivers/display_widgets.c
  src/main/drivers/display_widgets.h
  src/main/drivers/osd.c
  src/main/drivers/osd.h
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/displayport_frsky_osd.c
  src/main/io/frsky_osd.c
  src/main/io/frsky_osd.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_canvas.c
  src/main/io/osd_canvas.h
  src/main/io/osd_common.c
  src/main/io/osd_common.h
  src/main/io/osd_dji_hd.c
  src/main/io/osd_grid.c
  src/main/io/osd_grid.h
  src/main/io/osd_hud.c
  src/main/io/osd_hud.h
  src/main/io/serial.h
Labels: Release Notes

#5880 Allow using GPS altitude instead of barometer
  src/main/fc/fc_msp_box.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.h
  src/main/navigation/navigation_pos_estimator.c
Labels: Enhancement

#5928 Gyro EKF refactor
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/flight/kalman.c
  src/main/flight/kalman.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Cleanup/refactor

#6001 Bump the number of logic conditions to 32
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/programming/global_variables.c
  src/main/programming/global_variables.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Release Notes

#5995 Add safehomes
  docs/Safehomes.md
  src/main/config/parameter_group_ids.h
  src/main/fc/cli.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/target/common.h
Labels: Release Notes
