Repository iNavFlight/inav, pull requests merged in 2021-04, with the labels that each got.

#6783 Homogenize OSD AHI settings prefix
  docs/Settings.md
  src/main/fc/settings.yaml
Labels: Release Notes

#6792 Added rangefinder "GY-US42(v2) Ultrasonic Range Sensor"
  src/main/CMakeLists.txt
  src/main/drivers/bus.h
  src/main/drivers/bus_i2c_hal.c
  src/main/drivers/rangefinder/rangefinder_us42.c
  src/main/drivers/rangefinder/rangefinder_us42.h
  src/main/fc/settings.yaml
  src/main/sensors/rangefinder.c
  src/main/sensors/rangefinder.h
  src/main/target/MATEKF405SE/target.h
  src/main/target/common.h
  src/main/target/common_hardware.c
Labels: Release Notes

#6437 Fixed wing RTH Spiral Climb Option
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes

#6430 Fix Nav Launch detection related bugs
  src/main/flight/rth_estimator.c
  src/main/navigation/navigation_fw_launch.c
Labels: Ready to merge

#6821 Renamed OSD SW and LEDLOW to OSD/LEDS OFF
  src/main/fc/fc_msp_box.c
Labels: Release Notes

#6179 Switched RTH Preset Altitude Override
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Ready to merge, Release Notes

#6830 Fix error handling in settings.rb:Generator#resolve_types
  src/utils/settings.rb
Labels: BUG

#6812 DShot Beeper
  docs/Settings.md
  src/main/drivers/pwm_output.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/fc_tasks.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/io/beeper.c
  src/main/io/beeper.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
  src/main/io/serial_4way.c
  src/main/scheduler/scheduler.h
Labels: Release Notes

#6655 Delayed safehome
  docs/Safehomes.md
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/flight/failsafe.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Ready to merge

#6846 Drop gyro_sync
  docs/Settings.md
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/FALCORE/config.c
Labels: Release Notes

#6853 Copter: add new setting for final landing vspeed instead of being hardcoded to 25% of set landing vspeed
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Ready to merge, Release Notes

#6796 OSD: display power >1000W in kW
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
Labels: Release Notes

#6857 OSD: Fix bug in font metadata handling
  src/main/drivers/display_font_metadata.h
Labels: BUG

#6858 Add option to display min cell voltage instead of min pack voltage on the disarm screen
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Release Notes

#6900 Smith Compensator on PID measurement
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/smith_predictor.c
  src/main/flight/smith_predictor.h
  src/main/target/common.h
Labels: Experimental
