Repository iNavFlight/inav, pull requests merged in 2021-01, with the labels that each got.

#6469 Option for local plus codes on osd
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Release Notes

#6487 Remove unused UAV_INTERCONNECT
  src/main/CMakeLists.txt
  src/main/drivers/opflow/opflow_virtual.c
  src/main/drivers/rangefinder/rangefinder_virtual.c
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/io/serial.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/uib_rx.c
  src/main/rx/uib_rx.h
  src/main/scheduler/scheduler.h
  src/main/sensors/rangefinder.c
  src/main/sensors/rangefinder.h
  src/main/target/common.h
  src/main/uav_interconnect/uav_interconnect.h
  src/main/uav_interconnect/uav_interconnect_bus.c
  src/main/uav_interconnect/uav_interconnect_rangefinder.c
Labels: Cleanup/refactor

#6495 FLYWOOF411_V2 based on target files from vendor
  src/main/target/FLYWOOF411/CMakeLists.txt
  src/main/target/FLYWOOF411/target.c
  src/main/target/FLYWOOF411/target.h
Labels: Release Notes

#6341 Allow Logic Conditions to override RC channels
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
  src/main/rx/rx.c
Labels: Don't merge, Experimental, In progress

#6106 Added option to output servos on PWM and SBUS
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/pwm_output.c
  src/main/fc/config.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
Labels: Release Notes
