Repository iNavFlight/inav, pull requests merged in 2021-03, with the labels that each got.

#6658 Change PIDFF settings in CMS to UINT16
  src/main/cms/cms_menu_imu.c
Labels: BUG

#6664 Add an ability not to slow down when switching to the next waypoint
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_multicopter.c
Labels: Testing Required

#6669 Add D-term to control loop on fixed wing
  docs/Settings.md
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Experimental, Testing Required

#6695 Do not slow down in WP mission when approaching a waypoint
  src/main/navigation/navigation_multicopter.c
Labels: Release Notes
