Repository iNavFlight/inav, pull requests merged in 2021-07, with the labels that each got.

#7182 Release 3.0.1
  docs/Controls.md
  docs/assets/images/StickPositions.png
  docs/assets/images/StickPositions.svg
  src/main/common/calibration.c
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/fc/rc_controls.c
  src/main/flight/pid_autotune.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/target/MATEKH743/CMakeLists.txt
Labels: Don't merge

#7224 replace WP toggle with discrete commands
  docs/Controls.md
  docs/assets/images/StickPositions.png
  docs/assets/images/StickPositions.svg
  src/main/fc/rc_controls.c
Labels: Release Notes

#7265 Add support for RX5 on MATEKF765 target
  src/main/target/MATEKF765/target.h
Labels: Ready to merge

#7259 Add support for ICM42605 and ICM42688P IMUs
  src/main/CMakeLists.txt
  src/main/drivers/accgyro/accgyro_icm42605.c
  src/main/drivers/accgyro/accgyro_icm42605.h
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/bus.h
  src/main/fc/cli.c
  src/main/fc/settings.yaml
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/MATEKF765/CMakeLists.txt
  src/main/target/MATEKF765/target.c
  src/main/target/MATEKF765/target.h
  src/main/target/common_hardware.c
Labels: Ready to merge

#7282 [sensors/acceleration.c and sensors/gyro.c] Add X,Y and Z to array
  src/main/sensors/acceleration.c
  src/main/sensors/gyro.c
Labels: Cleanup/refactor, Ready to merge

#7155 [io/asyncfatfs/asyncfatfs.c] Fix name clashes in FAT filesystem
  src/main/io/asyncfatfs/asyncfatfs.c
Labels: Testing Required

#6823 Rate dynamics
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/build/debug.h
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile_config_struct.h
  src/main/fc/fc_core.c
  src/main/fc/settings.yaml
  src/main/flight/rate_dynamics.c
  src/main/flight/rate_dynamics.h
  src/main/target/common.h
Labels: Testing Required
