Repository iNavFlight/inav, pull requests merged in 2021-11, with the labels that each got.

#6765 Multi waypoint mission option
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/cli.c
  src/main/fc/fc_core.c
  src/main/fc/rc_controls.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_private.h
Labels: Ready to merge, Release Notes

#6938 Waypoint mission restart option
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_private.h
Labels: Ready to merge

#7574 Added PINIO and USER1 mode to FLYWOOF745 and FLYWOOF745
  src/main/target/FLYWOOF745/config.c
  src/main/target/FLYWOOF745/target.c
  src/main/target/FLYWOOF745/target.h
Labels: Ready to merge

#7323 Two Stage Climb First RTH
  docs/Navigation.md
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_private.h
Labels: Ready to merge, Release Notes

#7250 Fixed wing soaring mode
  docs/Settings.md
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
Labels: Release Notes

#6981 Add T-Motor F7 target.
  src/main/target/TMOTORF7/CMakeLists.txt
  src/main/target/TMOTORF7/target.c
  src/main/target/TMOTORF7/target.h
Labels: Unofficial Target

#7591 Sklip releases for Tmotor boards
  src/main/target/TMOTORF7/CMakeLists.txt
Labels: Ready to merge

#7461 Don't change P, I and D during FW autotune
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/flight/pid_autotune.c
Labels: Release Notes
