Repository iNavFlight/inav, pull requests merged in 2021-06, with the labels that each got.

#7090 Fix Dshot beeper - active with non Dshot ESC protocols
  src/main/io/beeper.c
Labels: BUG

#7075 Fix power limits
  src/main/flight/power_limits.c
Labels: BUG

#7086 Dzikuvx potential fix for bb problems
  src/main/scheduler/scheduler.c
Labels: Testing Required

#6819 Update to total length of average and variance windows
  src/main/flight/kalman.c
  src/main/flight/kalman.h
Labels: Testing Required

#7048 Add the possibility to link a control rate profile to a battery profile
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/fc/controlrate_profile.h
  src/main/fc/controlrate_profile_config_struct.h
  src/main/fc/settings.yaml
  src/main/sensors/battery.c
  src/main/sensors/battery.h
Labels: Ready to merge

#7162 Fix bug that doesn't allow arming with ALLOW_BYPASS
  src/main/fc/fc_core.c
Labels: BUG

#7151 Always apply MR ControlDerivative
  src/main/flight/pid.c
Labels: Testing Required

#7204 reimplement stick mission load as toggle; update RC control images an…
  docs/Controls.md
  docs/assets/images/StickPositions.png
  docs/assets/images/StickPositions.svg
  src/main/fc/rc_controls.c
Labels: Release Notes
