Repository iNavFlight/inav, pull requests merged in 2021-05, with the labels that each got.

#6902 Alpha-Beta-Gamma filter for gyro
  docs/Settings.md
  src/main/build/debug.h
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common.h
Labels: Experimental

#6662 WP mission sealevel altitude datum
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes

#6822 WP Mission Landing Elevation Setting
  src/main/navigation/navigation.c
Labels: Release Notes

#6904 Add CRUISE mode which is equivalent to CRSH+AH
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/navigation/navigation.c
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Release Notes

#6828 Gyro processing improvements
  docs/Settings.md
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_io.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/flight/servos.c
  src/main/io/osd_dji_hd.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/FALCORE/config.c
  src/test/unit/scheduler_unittest.cc.txt
  src/test/unit/sensor_gyro_unittest.cc
Labels: Release Notes

#4442 Set max allowed altitude for both FW and MR
  docs/Cli.md
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Enhancement, Release Notes

#6930 CMS: fix some and add missing items in OSD menu
  src/main/cms/cms_menu_osd.c
Labels: BUG

#6866 Mamaba F722_I2C target
  src/main/target/MAMBAF722/CMakeLists.txt
  src/main/target/MAMBAF722/config.c
  src/main/target/MAMBAF722/target.h
Labels: Release Notes

#6867 Diatone MambaF405US_I2C target
  src/main/target/MAMBAF405US/CMakeLists.txt
  src/main/target/MAMBAF405US/config.c
  src/main/target/MAMBAF405US/target.c
  src/main/target/MAMBAF405US/target.h
Labels: Release Notes

#6708 Automatic servo trim
  docs/Settings.md
  src/main/build/debug.h
  src/main/fc/cli.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/fc_msp_box.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/servos.c
  src/main/flight/servos.h
Labels: Ready to merge, Release Notes

#6936 Fix mistake in #6904
  src/main/fc/fc_msp_box.c
Labels: BUG

#6929 Add power limits
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/cms/cms_menu_osd.c
  src/main/config/parameter_group_ids.h
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/flight/power_limits.c
  src/main/flight/power_limits.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/sensors/battery.c
  src/main/sensors/battery.h
  src/main/target/common.h
Labels: Feature request, Release Notes

#6681 FW autotune improvements
  docs/Settings.md
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_autotune.c
Labels: Release Notes, Testing Required

#6942 OSD HUD Crosshairs bug fix
  src/main/io/osd.c
Labels: BUG

#6564 Autolevel flight mode and pitch trim option
  docs/Settings.md
  src/main/build/debug.h
  src/main/common/fp_pid.c
  src/main/common/fp_pid.h
  src/main/fc/fc_msp_box.c
  src/main/fc/fc_tasks.c
  src/main/fc/rc_modes.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Testing Required

#6612 Automatically load waypoints during FC boot
  docs/Controls.md
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes

#7021 Fix bug that D-term was not active on fixed-wing
  src/main/flight/pid.c
Labels: BUG
