Repository iNavFlight/inav, pull requests merged in 2021-12, with the labels that each got.

#7649 Mamba H743 target
  src/main/target/MAMBAH743/CMakeLists.txt
  src/main/target/MAMBAH743/config.c
  src/main/target/MAMBAH743/target.c
  src/main/target/MAMBAH743/target.h
Labels: In progress, Don't merge

#7640 Speedybee F7 MINI target
  src/main/target/SPEEDYBEEF7MINI/CMakeLists.txt
  src/main/target/SPEEDYBEEF7MINI/config.c
  src/main/target/SPEEDYBEEF7MINI/target.c
  src/main/target/SPEEDYBEEF7MINI/target.h
Labels: In progress

#7617 Remove USE_NAV define
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_navigation.c
  src/main/drivers/irlock.c
  src/main/drivers/irlock.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_modes.c
  src/main/fc/settings.yaml
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/flight/pid.c
  src/main/io/dashboard.c
  src/main/io/osd.c
  src/main/io/osd_dji_hd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_fw_launch.c
  src/main/navigation/navigation_geo.c
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_pos_estimator_agl.c
  src/main/navigation/navigation_pos_estimator_flow.c
  src/main/navigation/navigation_private.h
  src/main/navigation/navigation_rover_boat.c
  src/main/rx/eleres.c
  src/main/sensors/irlock.c
  src/main/sensors/irlock.h
  src/main/target/ANYFCF7/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/common.h
  src/main/telemetry/jetiexbus.c
  src/main/telemetry/ltm.c
  src/main/telemetry/ltm.h
  src/main/telemetry/mavlink.c
  src/main/telemetry/sim.c
Labels: Don't merge

#7597 Matrix filter rework
  src/main/flight/dynamic_gyro_notch.c
  src/main/flight/dynamic_gyro_notch.h
  src/main/flight/gyroanalyse.c
  src/main/flight/gyroanalyse.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Testing Required

#7683 h7: switch spi to LL implementation
  cmake/stm32h7.cmake
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/bus_spi_hal_ll.c
  src/main/target/KAKUTEH7/target.h
Labels: Testing Required
