Repository iNavFlight/inav, pull requests merged in 2021-02, with the labels that each got.

#6550 AFATFS: fix freadSync
  src/main/io/asyncfatfs/asyncfatfs.c
Labels: BUG

#6458 added vtx_smartaudio_early_akk_workaround option
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
  src/main/io/vtx_smartaudio.c
Labels: Release Notes

#6568 Ability to trim pitch angle for level flight
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Release Notes

#6578 Removed mc_ from airmode CLI variables
  docs/Settings.md
  src/main/fc/settings.yaml
Labels: Release Notes

#6581 Increased fw loiter radius default
  src/main/navigation/navigation.c
Labels: Release Notes

#6584 Enable baro median filtering by default again
  src/main/sensors/barometer.c
Labels: BUG

#6602 Fix logic condition VSpeed constraint not allowing the value to be negative
  src/main/programming/logic_condition.c
Labels: BUG

#6636 Fix mag gain computation for negative mag zero
  src/main/sensors/compass.c
Labels: Release Notes

#6501 Pan servo home direction offset
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Release Notes

#6407 TURN ASSIST improvements for Fixed Wing
  src/main/flight/pid.c
Labels: Enhancement

#6387 Freeze yaw I-term above bank angle threshold
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Ready to merge, Release Notes

#6610 Allow to configure speed source for DJI OSD
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd_common.c
  src/main/io/osd_common.h
  src/main/io/osd_dji_hd.c
  src/main/io/osd_dji_hd.h
  src/main/programming/logic_condition.c
Labels: Release Notes

#6562 [FEATURE] Prearm
  src/main/fc/fc_core.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
Labels: Release Notes

#6180 Add driver for BMI088 IMU
  src/main/CMakeLists.txt
  src/main/drivers/accgyro/accgyro_bmi088.c
  src/main/drivers/accgyro/accgyro_bmi088.h
  src/main/drivers/bus.h
  src/main/fc/settings.yaml
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common_hardware.c
Labels: Release Notes
