Repository iNavFlight/inav, pull requests merged in 2022-08, with the labels that each got.

#8280 Enforce waypoint altitude tolerance fix
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes

#8234 Improved fixed wing waypoint course tracking
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/common/maths.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_private.h
Labels: Ready to merge

#8317 Speedybee F7 V3
  src/main/target/SPEEDYBEEF7V3/CMakeLists.txt
  src/main/target/SPEEDYBEEF7V3/config.c
  src/main/target/SPEEDYBEEF7V3/target.c
  src/main/target/SPEEDYBEEF7V3/target.h
Labels: Release Notes

#8321 AtomRC F405 NAVI target
  src/main/target/ATOMRCF405NAVI/CMakeLists.txt
  src/main/target/ATOMRCF405NAVI/target.c
  src/main/target/ATOMRCF405NAVI/target.h
Labels: Release Notes

#8335 iFlight BLITZF7PRO target
  src/main/target/IFLIGHT_BLITZ_F7_PRO/CMakeLists.txt
  src/main/target/IFLIGHT_BLITZ_F7_PRO/target.c
  src/main/target/IFLIGHT_BLITZ_F7_PRO/target.h
Labels: Release Notes

#8334 iFlight JBF7PRO target
  src/main/target/IFLIGHT_JBF7PRO/CMakeLists.txt
  src/main/target/IFLIGHT_JBF7PRO/config.c
  src/main/target/IFLIGHT_JBF7PRO/target.c
  src/main/target/IFLIGHT_JBF7PRO/target.h
Labels: Release Notes

#8186 INAV 5.1.0 Release branch
  docs/Cli.md
  docs/boards/MatekF405 Wing.md
  src/main/fc/cli.c
  src/main/navigation/navigation.c
  src/main/programming/logic_condition.c
  src/main/sensors/esc_sensor.h
  src/main/target/ATOMRCF405NAVI/CMakeLists.txt
  src/main/target/ATOMRCF405NAVI/target.c
  src/main/target/ATOMRCF405NAVI/target.h
  src/main/target/IFLIGHT_BLITZ_F7_PRO/CMakeLists.txt
  src/main/target/IFLIGHT_BLITZ_F7_PRO/target.c
  src/main/target/IFLIGHT_BLITZ_F7_PRO/target.h
  src/main/target/IFLIGHT_JBF7PRO/CMakeLists.txt
  src/main/target/IFLIGHT_JBF7PRO/config.c
  src/main/target/IFLIGHT_JBF7PRO/target.c
  src/main/target/IFLIGHT_JBF7PRO/target.h
  src/main/target/MATEKF405SE/CMakeLists.txt
  src/main/target/MATEKF405SE/README.md
  src/main/target/MATEKF405SE/config.c
  src/main/target/MATEKF405SE/target.h
  src/main/target/SPEEDYBEEF7V3/CMakeLists.txt
  src/main/target/SPEEDYBEEF7V3/config.c
  src/main/target/SPEEDYBEEF7V3/target.c
  src/main/target/SPEEDYBEEF7V3/target.h
Labels: Don't merge
