Repository iNavFlight/inav, pull requests merged in 2022-02, with the labels that each got.

#7803 Added some comparative operations to Programming
  docs/Programming Framework.md
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator

#7681 Release 4.1
  CMakeLists.txt
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/target/MAMBAF722_X8/CMakeLists.txt
  src/main/target/MAMBAF722_X8/config.c
  src/main/target/MAMBAF722_X8/target.c
  src/main/target/MAMBAF722_X8/target.h
  src/main/target/MATEKH743/target.c
Labels: Don't merge

#7852 Drop MSP_CF_SERIAL_CONFIG and MSP_SET_CF_SERIAL_CONFIG frames
  src/main/fc/fc_msp.c
  src/main/msp/msp_protocol.h
Labels: Release Notes
