Repository iNavFlight/inav, pull requests merged in 2022-11, with the labels that each got.

#8401 Add PINIO 3 & 4 plus MATEKF722PX_PINIO target
  docs/boards/Matek F722PX-WPX-HD.md
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_modes.h
  src/main/io/piniobox.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
  src/main/target/MATEKF722PX/CMakeLists.txt
  src/main/target/MATEKF722PX/config.c
  src/main/target/MATEKF722PX/target.h
Labels: Requires Configurator

#8529 Use course over ground as the default for fixed wing navigation "heading"
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_pos_estimator_private.h
Labels: In progress

#8451 Remove unnecessary parameters from profiles
  src/main/fc/rc_adjustments.c
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/io/osd.c
  src/main/io/osd_dji_hd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/sensors/battery.c
  src/main/sensors/battery_config_structs.h
Labels: Requires Configurator

#8589 Increase nav_wp_safe_distance maximum
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
Labels: Release Notes, Requires Configurator
