Repository iNavFlight/inav, pull requests merged in 2022-12, with the labels that each got.

#8581 Add EDGE, DELAY, DELTA, APPROX_EQUAL switches and TIMER to Logic Conditions
  docs/Programming Framework.md
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator

#8584 Add symbols for remaining time/distance
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
Labels: Requires Configurator, Font change

#8585 Change logo size for future enhancements
  src/main/drivers/osd_symbols.h
Labels: Requires Configurator, Font change

#8604 OSD Ground Course and Cross Track Error
  src/main/cms/cms_menu_osd.c
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_private.h
Labels: Requires Configurator, Font change

#8611 Stop allowing navigation modes to be active while arming.
  src/main/navigation/navigation.c
Labels: Release Notes

#8628 Kakute H7 V2 Invert PINIO2 so VTX is ON by default
  src/main/target/KAKUTEH7/target.h
Labels: Release Notes
