Repository iNavFlight/inav, pull requests merged in 2022-07, with the labels that each got.

#8181 Remove an unused definition
  src/main/fc/fc_msp.c
  src/main/target/MAMBAF405US/target.h
  src/main/target/MAMBAF405_2022A/target.h
  src/main/target/MAMBAF722/target.h
  src/main/target/MAMBAF722_2022A/target.h
  src/main/target/MAMBAF722_X8/target.h
Labels: Cleanup/refactor

#8173 Drop SPI RX as not used by any supported hardware
  docs/Cli.md
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/config/parameter_group_ids.h
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/drivers/rx_spi.c
  src/main/drivers/rx_spi.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/rx/eleres.c
  src/main/rx/eleres.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
Labels: Cleanup/refactor

#8189 Remove unused rxRefreshRate
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/fport2.c
  src/main/rx/ghst.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/mavlink.c
  src/main/rx/msp.c
  src/main/rx/msp_override.c
  src/main/rx/msp_override.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/srxl2.c
  src/main/rx/sumd.c
  src/main/rx/sumh.c
Labels: Cleanup/refactor

#8185 Configurator: Reset PIDs button to use applied defaults
  docs/Settings.md
  src/main/config/general_settings.h
  src/main/fc/settings.yaml
Labels: Requires Configurator

#8197 Log gyro noise peaks as separate fields
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/blackbox/blackbox_fielddefs.h
  src/main/build/debug.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/settings.yaml
  src/main/flight/dynamic_gyro_notch.c
  src/main/flight/dynamic_gyro_notch.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Release Notes

#8198 Drop SUMH RX protocol
  docs/Rx.md
  src/main/CMakeLists.txt
  src/main/fc/settings.yaml
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sumh.c
  src/main/rx/sumh.h
  src/main/target/common.h
  src/test/unit/rx_ranges_unittest.cc.txt
Labels: Release Notes

#8166 Support for Flash Memory W25N01G of 128MB
  src/bl/bl_main.c
  src/main/CMakeLists.txt
  src/main/blackbox/blackbox_io.c
  src/main/drivers/bus.h
  src/main/drivers/flash.c
  src/main/drivers/flash.h
  src/main/drivers/flash_m25p16.c
  src/main/drivers/flash_w25n01g.c
  src/main/drivers/flash_w25n01g.h
  src/main/fc/fc_init.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
  src/main/target/MAMBAH743/target.h
  src/main/target/ZEEZF7/target.h
  src/main/target/common_hardware.c
Labels: Release Notes

#8221 Remove unused header file
  src/main/config/config_unittest.h
Labels: Cleanup/refactor

#8213 Drop the MPU-6050 Support
  src/main/CMakeLists.txt
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_mpu6050.c
  src/main/drivers/accgyro/accgyro_mpu6050.h
  src/main/drivers/bus.h
  src/main/fc/cli.c
  src/main/fc/settings.yaml
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common_hardware.c
  src/main/target/sanity_check.h
Labels: Cleanup/refactor

#8212 RC interpolation updates
  docs/Settings.md
  src/main/blackbox/blackbox.c
  src/main/fc/fc_core.c
  src/main/fc/fc_tasks.c
  src/main/fc/rc_smoothing.c
  src/main/fc/rc_smoothing.h
  src/main/fc/settings.yaml
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: Release Notes

#8215 [config_eeprom.c] Replace a function with another one that already exists in the library
  src/main/config/config_eeprom.c
Labels: Cleanup/refactor

#8226 Make HUD offset more intuitive
  src/main/io/osd.c
Labels: Release Notes

#8134 Nav launch manual throttle option
  docs/Settings.md
  src/main/cms/cms_menu_navigation.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_fw_launch.c
Labels: Ready to merge, Release Notes

#8230 Remove some NO optimizations made by MCU_FLASH_SIZE
  src/main/common/log.h
  src/main/fc/cli.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/target/common.h
  src/main/target/common_post.h
Labels: Cleanup/refactor

#8081 Add glide time, glide distance, and climb efficiency OSD elements
  src/main/common/constants.h
  src/main/drivers/osd_symbols.h
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Ready to merge, Requires Configurator, Font change
