Repository iNavFlight/inav, pull requests merged in 2022-05, with the labels that each got.

#7949 Matek 1G3SE control via IRC Tramp
  docs/Settings.md
  docs/VTx.md
  src/main/drivers/vtx_common.h
  src/main/fc/settings.yaml
  src/main/io/vtx.c
  src/main/io/vtx.h
  src/main/io/vtx_string.c
  src/main/io/vtx_string.h
  src/main/io/vtx_tramp.c
  src/main/io/vtx_tramp.h
Labels: Ready to merge, Release Notes

#7972 ESP32 Radar: Added support for missing OSD unit types
  src/main/io/osd_hud.c
Labels: Testing Required

#7868 Enhance mAh Used OSD Element
  docs/Settings.md
  src/main/drivers/osd_symbols.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Enhancement, Ready to merge, Requires Configurator, Font change

#7889 New target JHEMCU GH743AIO / iFlight Beast H7 55A AIO
  src/main/target/JHEH7AIO/CMakeLists.txt
  src/main/target/JHEH7AIO/config.c
  src/main/target/JHEH7AIO/target.c
  src/main/target/JHEH7AIO/target.h
Labels: Unofficial Target

#7962 iFlight Beast H7 V2 I2C2 on UART 3
  src/main/target/IFLIGHT_H743_AIO_V2/CMakeLists.txt
  src/main/target/IFLIGHT_H743_AIO_V2/config.c
  src/main/target/IFLIGHT_H743_AIO_V2/target.c
  src/main/target/IFLIGHT_H743_AIO_V2/target.h
Labels: Unofficial Target

#7984 Dzikuvx add rangefinder to logic conditions
  docs/Programming Framework.md
  src/main/navigation/navigation.h
  src/main/navigation/navigation_pos_estimator.c
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Release Notes

#7985 TBS Sixty9 SA2.1 UART Configuration
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
  src/main/io/vtx_smartaudio.c
Labels: Release Notes

#8022 Increase Logic Conditions to 64
  src/main/programming/logic_condition.h
Labels: Ready to merge, Requires Configurator

#8023 Added Fixed Wing TPA Time Constant to in flight adjustments
  docs/Inflight Adjustments.md
  docs/Settings.md
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Requires Configurator

#8032 Drop PCA9685 support
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/drivers/bus.h
  src/main/drivers/io_pca9685.c
  src/main/drivers/io_pca9685.h
  src/main/drivers/lights_io.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/pwm_output.c
  src/main/fc/config.c
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/flight/servos.c
  src/main/io/pwmdriver_i2c.c
  src/main/io/pwmdriver_i2c.h
  src/main/scheduler/scheduler.h
  src/main/target/AIKONF4/target.h
  src/main/target/AIRBOTF4/target.h
  src/main/target/ALIENFLIGHTF3/target.h
  src/main/target/ANYFC/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/ANYFCM7/target.h
  src/main/target/ASGARD32F4/target.h
  src/main/target/ASGARD32F7/target.h
  src/main/target/BETAFLIGHTF4/target.h
  src/main/target/COLIBRI_RACE/target.h
  src/main/target/F4BY/target.h
  src/main/target/FALCORE/target.h
  src/main/target/FIREWORKSV2/target.h
  src/main/target/FURYF4OSD/target.h
  src/main/target/IFLIGHTF4_TWING/target.h
  src/main/target/LUX_RACE/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF405CAN/target.h
  src/main/target/MATEKF405SE/target.h
  src/main/target/MATEKF405TE/target.h
  src/main/target/MOTOLAB/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/RCEXPLORERF3/target.h
  src/main/target/REVO/target.h
  src/main/target/SKYSTARSF405HD/target.h
  src/main/target/SPARKY/target.h
  src/main/target/SPARKY2/target.h
  src/main/target/YUPIF4/target.h
  src/main/target/common.h
  src/main/target/common_hardware.c
Labels: Release Notes

#8028 Added FW level trim to in flight adjustments
  docs/Inflight Adjustments.md
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Requires Configurator

#8033 Kakute H7 Mini target
  src/main/target/KAKUTEH7/CMakeLists.txt
  src/main/target/KAKUTEH7/config.c
  src/main/target/KAKUTEH7/target.h
Labels: Release Notes

#8051 Fixed typos
  docs/Programming Framework.md
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator

#8027 Allow pilot to define the time shown for alt differential and distance with Radar
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_hud.c
Labels: Ready to merge
