Repository iNavFlight/inav, pull requests merged in 2022-09, with the labels that each got.

#8393 Treat wp.p3 as bitfield
  docs/Navigation.md
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Release Notes, Requires Configurator

#8394 Re-order boxmodes to have as little disruption to 5.1 as possible
  src/main/fc/fc_msp_box.c
Labels: Release Notes

#8354 Waypoint multi-mission in flight mission change
  docs/Settings.md
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/fc/rc_modes.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_private.h
Labels: Ready to merge
