Repository iNavFlight/inav, pull requests merged in 2023-10, with the labels that each got.

#9335 Add odometer to OSD
  src/main/common/maths.h
  src/main/drivers/osd_symbols.h
  src/main/fc/stats.h
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_hud.c
  src/main/io/osd_utils.c
  src/main/io/osd_utils.h
  src/main/navigation/navigation.c
  src/test/unit/osd_unittest.cc
Labels: Requires Configurator, Font change

#9332 Add pilot logo to OSD
  docs/Settings.md
  src/main/cms/cms.h
  src/main/drivers/osd_symbols.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Requires Configurator, Font change

#9254 In flight emergency rearm
  src/main/fc/fc_core.c
  src/main/fc/runtime_config.h
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_pos_estimator.c
Labels: Testing Required

#9393 FW Auto level trim bug fix
  src/main/fc/fc_core.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/io/osd.c
Labels: BUG

#8956 New target: ATOMRC Exceed F405 FC V2
  src/main/target/ATOMRCF405V2/CMakeLists.txt
  src/main/target/ATOMRCF405V2/target.c
  src/main/target/ATOMRCF405V2/target.h
Labels: Unofficial Target
