Repository iNavFlight/inav, pull requests merged in 2023-08, with the labels that each got.

#9166 MSP VTX support
  src/main/CMakeLists.txt
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/io/displayport_msp_osd.c
  src/main/io/displayport_msp_osd.h
  src/main/io/serial.h
  src/main/io/vtx_control.c
  src/main/io/vtx_msp.c
  src/main/io/vtx_msp.h
  src/main/msp/msp_protocol.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/target/SITL/target.h
  src/main/target/common.h
Labels: Enhancement

#9169 Multicopter emergency landing improvement/fix
  src/main/navigation/navigation_multicopter.c
Labels: Testing Required

#9214 SKYSTARSH743HD remove non-existent S9 & S10. Add servos target
  src/main/target/SKYSTARSH743HD/CMakeLists.txt
  src/main/target/SKYSTARSH743HD/target.c
Labels: Release Notes

#8698 Multi function OSD utility
  src/main/CMakeLists.txt
  src/main/drivers/osd_symbols.h
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/fc_msp_box.c
  src/main/fc/multifunction.c
  src/main/fc/multifunction.h
  src/main/fc/rc_controls.c
  src/main/fc/rc_modes.h
  src/main/flight/failsafe.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_pos_estimator.c
  src/main/navigation/navigation_private.h
  src/main/target/common.h
Labels: Testing Required, Requires Configurator, Font change
