Repository iNavFlight/inav, pull requests merged in 2023-09, with the labels that each got.

#9265 Timer DMA burst
  src/main/drivers/pwm_output.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/drivers/timer_impl.h
  src/main/drivers/timer_impl_hal.c
  src/main/drivers/timer_impl_stdperiph.c
  src/main/target/SPEEDYBEEF405V3/target.h
Labels: Release Notes

#9213 Multirotor course hold/cruise mode
  docs/Settings.md
  src/main/fc/fc_msp_box.c
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/io/osd.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Release Notes

#9277 Switch MatekF405TE to use burst DMA
  src/main/target/MATEKF405TE/target.h
Labels: Release Notes

#9281 BETAFPVF435 unofficial target
  src/main/io/ledstrip.h
  src/main/target/BETAFPVF435/CMakeLists.txt
  src/main/target/BETAFPVF435/config.c
  src/main/target/BETAFPVF435/target.c
  src/main/target/BETAFPVF435/target.h
Labels: Unofficial Target

#9268 Make PWM allocation a bit smarter.
  docs/Cli.md
  docs/ESC and servo outputs.md
  src/main/config/parameter_group_ids.h
  src/main/drivers/pwm_mapping.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/target/MATEKF405/CMakeLists.txt
  src/main/target/MATEKF405/target.c
  src/main/target/MATEKF722/CMakeLists.txt
  src/main/target/MATEKF722/target.c
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKH743/target.c
Labels: Release Notes, Requires Configurator

#9300 Drop output_mode setting
  docs/Settings.md
  src/main/drivers/pwm_mapping.c
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
Labels: Release Notes

#9288 Further simplify timer usage flags.
  src/main/drivers/pwm_esc_detect.c
  src/main/drivers/pwm_mapping.c
  src/main/drivers/timer.h
Labels: Requires Configurator

#8555 Mixer profile to open the posibility for vtol/mixed platform
  .gitignore
  docs/MixerProfile.md
  docs/Screenshots/mixer_profile.png
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/cms/cms_menu_mixer_servo.c
  src/main/config/parameter_group_ids.h
  src/main/drivers/pwm_mapping.h
  src/main/fc/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_modes.h
  src/main/fc/settings.c
  src/main/fc/settings.h
  src/main/fc/settings.yaml
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_profile.c
  src/main/flight/mixer_profile.h
  src/main/flight/pid.c
  src/main/flight/pid_autotune.c
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_private.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
  src/main/programming/programming_task.c
  src/main/sensors/battery.c
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/FF_F35_LIGHTNING/config.c
  src/main/target/MATEKF405SE/config.c
  src/main/target/SITL/target.h
  src/main/target/common.h
  src/main/telemetry/mavlink.c
Labels: Experimental

#9320 Add SouthPAN SBAS for all my friends in AU/NZ.
  src/main/fc/settings.yaml
  src/main/io/gps.h
  src/main/io/gps_ublox.c
Labels: Release Notes, Requires Configurator

#9302 Drop NMEA protocol
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/fc/settings.yaml
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_nmea.c
  src/main/io/gps_private.h
  src/main/target/common.h
  src/main/telemetry/telemetry.h
  src/test/unit/target.h
  src/utils/rename-ifdefs.py
Labels: Release Notes

#9325 SpeedyBEEF405WING Change S11 timer, since TIM1 is used by LED
  src/main/target/SPEEDYBEEF405WING/target.c
Labels: Testing Required
