Repository iNavFlight/inav, pull requests merged in 2023-01, with the labels that each got.

#8624 OSD Heading field fix + field display index update
  src/main/io/osd.c
Labels: Testing Required

#8680 Update RUSH_BLADE_F7 and add RUSH_BLADE_F7_HD targets
  src/main/target/RUSH_BLADE_F7/CMakeLists.txt
  src/main/target/RUSH_BLADE_F7/target.c
  src/main/target/RUSH_BLADE_F7/target.h
Labels: Release Notes

#8579 Enhance programming options for waypoint missions
  docs/Programming Framework.md
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Enhancement, Release Notes, Requires Configurator

#8654 Update MSPDisplayPort and add Walksnail Avatar settings
  docs/Settings.md
  src/main/common/time.h
  src/main/drivers/osd.h
  src/main/fc/settings.yaml
  src/main/io/displayport_msp.h
  src/main/io/displayport_msp_osd.c
  src/main/io/displayport_msp_osd.h
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Requires Configurator

#8586 FW Nav Course Hold control method change
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_private.h
Labels: Testing Required

#8711 Disarm on land by default
  docs/Settings.md
  src/main/fc/settings.yaml
Labels: Release Notes

#8536 Add strobe overlay to RGB LEDs
  docs/LedStrip.md
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/main/msp/msp_protocol.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/target/OMNIBUSF7NXT/config.c
Labels: Enhancement, Release Notes, Requires Configurator

#8720 Add pilot name
  docs/Settings.md
  src/main/blackbox/blackbox.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
Labels: Requires Configurator

#8686 Manual emergency landing FW and MR
  src/main/flight/failsafe.c
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Testing Required

#8747 Update Flight Mode operand in programming framework
  docs/Programming Framework.md
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator
