Repository iNavFlight/inav, pull requests merged in 2023-04, with the labels that each got.

#8896 Navigation altitude and position controller reset improvements
  src/main/navigation/navigation.c
Labels: Ready to merge

#8826 Fix LED Indicators mode for Fixed Wing and Rover
  docs/LedStrip.md
  src/main/io/ledstrip.c
Labels: Enhancement

#8810 Enhance Linear Descent RTH feature
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
Labels: Ready to merge, Release Notes, Requires Configurator

#8972 Rename AUTO LEVEL
  src/main/fc/fc_msp_box.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
Labels: Release Notes, Requires Configurator

#9007 Fix issue with DJI O3 showing miles instead of kFt
  src/main/io/osd.c
Labels: Ready to merge
