Repository iNavFlight/inav, pull requests merged in 2024-11, with the labels that each got.

#10451 Initial implementation of MSP RC stats and info messages
  docs/Settings.md
  src/main/cms/cms_menu_osd.c
  src/main/common/streambuf.c
  src/main/common/streambuf.h
  src/main/drivers/osd_symbols.h
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/msp/msp_protocol_v2_common.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: Requires Configurator

#10459 Geozones (aka Geofence)
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/common/vector.h
  src/main/config/parameter_group_ids.h
  src/main/fc/cli.c
  src/main/fc/config.h
  src/main/fc/fc_core.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_tasks.c
  src/main/fc/runtime_config.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
  src/main/msp/msp_protocol_v2_inav.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_geozone.c
  src/main/navigation/navigation_private.h
  src/main/scheduler/scheduler.h
  src/main/target/SITL/target.h
  src/main/target/common.h
Labels: In progress

#10466 Geozones.md
  docs/Geozones.md
Labels: Ready to merge

#10454 add TBS_LUCID_H7
  src/main/target/TBS_LUCID_H7/CMakeLists.txt
  src/main/target/TBS_LUCID_H7/config.c
  src/main/target/TBS_LUCID_H7/target.c
  src/main/target/TBS_LUCID_H7/target.h
Labels: New target

#9556 Add BF config to INAV target converter
  docs/development/Converting Betaflight Targets.md
  src/utils/bf2inav.py
  src/utils/timer_pins.yaml
Labels: Testing Required

#10469 Add support for SKYSTARSSF405AIO target
  src/main/target/SKYSTARSF405HD/CMakeLists.txt
  src/main/target/SKYSTARSF405HD/config.c
  src/main/target/SKYSTARSF405HD/target.c
  src/main/target/SKYSTARSF405HD/target.h
Labels: New target
