Repository iNavFlight/inav, pull requests merged in 2024-09, with the labels that each got.

#10278 Waypoint tracking improvements
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/navigation/navigation_fixedwing.c
Labels: Requires Configurator

#10333 at32: add uart pinswap
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_at32f43x.c
  src/main/drivers/serial_uart_hal_at32f43x.c
  src/main/target/NEUTRONRCF435MINI/target.h
Labels: Don't merge

#10282 Enhance OSD Custom Elements
  docs/OSD.md
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd/custom_elements.c
  src/main/io/osd/custom_elements.h
  src/main/msp/msp_protocol_v2_inav.h
Labels: Release Notes, Requires Configurator, MSP Breaking Change

#10215 Further tweaks to mavlink
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/telemetry/mavlink.c
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
Labels: Testing Required
