Repository iNavFlight/inav, pull requests merged in 2024-03, with the labels that each got.

#9815 Betafpvf411 unofficial
  src/main/target/BETAFPVF411/CMakeLists.txt
  src/main/target/BETAFPVF411/target.c
  src/main/target/BETAFPVF411/target.h
Labels: Unofficial Target

#9848 Add target to switch to second gyro on MAMBAH743_2022B, instead of first gyro
  docs/boards/MAMBAH743_2022B.md
  src/main/target/MAMBAH743/CMakeLists.txt
  src/main/target/MAMBAH743/target.c
  src/main/target/MAMBAH743/target.h
Labels: Release Notes

#9851 Add missing outputs for SKYSTARSHD2
  src/main/target/SKYSTARSF405HD/CMakeLists.txt
  src/main/target/SKYSTARSF405HD/target.c
  src/main/target/SKYSTARSF405HD/target.h
Labels: Testing Required
