Repository iNavFlight/inav, pull requests merged in 2024-05, with the labels that each got.

#9978 Add GEPRCF745_BT_HD target
  src/main/target/GEPRCF745_BT_HD/CMakeLists.txt
  src/main/target/GEPRCF745_BT_HD/config.c
  src/main/target/GEPRCF745_BT_HD/target.c
  src/main/target/GEPRCF745_BT_HD/target.h
Labels: New target

#9471 Fixed wing Nav altitude velocity control
  docs/Settings.md
  src/main/cms/cms_menu_imu.c
  src/main/fc/fc_msp.c
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_multicopter.c
  src/main/navigation/navigation_private.h
Labels: Ready to merge

#9905 I-Term Lock for Fixed Wing
  docs/Settings.md
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Release Notes

#10022 Allow LED pin to be reassigned as MOTOR or SERVO
  .vimrc
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/pwm_mapping.c
  src/main/drivers/pwm_mapping.h
  src/main/drivers/timer.h
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/flight/mixer.h
  src/main/msp/msp_protocol_v2_inav.h
  src/main/target/AIRBOTF7/target.c
  src/main/target/ANYFCM7/target.c
  src/main/target/BLUEJAYF4/target.c
  src/main/target/F4BY/target.c
  src/main/target/FOXEERF745AIO/target.c
  src/main/target/FRSKYPILOT/target.c
  src/main/target/IFLIGHT_BLITZ_ATF435/target.c
  src/main/target/MATEKF405/target.c
  src/main/target/NEUTRONRCF435MINI/target.c
  src/main/target/NEUTRONRCF435WING/target.c
  src/main/target/OMNIBUSF4/CMakeLists.txt
  src/main/target/OMNIBUSF4/target.c
  src/main/target/SAGEATF4/target.c
  src/main/target/SPEEDYBEEF405MINI/CMakeLists.txt
  src/main/target/SPEEDYBEEF405MINI/target.c
  src/main/target/SPRACINGF7DUAL/target.c
  src/main/target/TAKERF722SE/target.c
  src/main/target/TMOTORF7V2/target.c
  src/main/target/TMOTORVELOXF7V2/target.c
Labels: Requires Configurator
