Repository iNavFlight/inav, pull requests merged in 2024-07, with the labels that each got.

#10183 Add flown loiter radius to programming logic
  docs/Programming Framework.md
  src/main/navigation/navigation.c
  src/main/navigation/navigation.h
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator

#10179 [GPS] Fix message rate for newer ublox devices and add some extra debugging features
  src/main/build/debug.h
  src/main/common/printf.c
  src/main/fc/cli.c
  src/main/fc/settings.yaml
  src/main/io/gps_private.h
  src/main/io/gps_ublox.c
  src/main/io/gps_ublox.h
  src/main/io/gps_ublox_utils.c
  src/main/io/gps_ublox_utils.h
  src/test/unit/gps_ublox_unittest.cc
Labels: In progress

#10186 Make LULU smoother independent from the gyro LPF
  docs/Settings.md
  src/main/build/debug.h
  src/main/fc/settings.yaml
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Experimental

#10214 [GPS] UBLOX and UBLOX7 have been merged into UBLOX
  src/main/fc/settings.yaml
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_ublox.c
Labels: Release Notes

#10198 Add new targets: MicoAir405Mini, MicoAir405v2 and MicoAir743
  src/main/target/MICOAIR405MINI/CMakeLists.txt
  src/main/target/MICOAIR405MINI/config.c
  src/main/target/MICOAIR405MINI/target.c
  src/main/target/MICOAIR405MINI/target.h
  src/main/target/MICOAIR405V2/CMakeLists.txt
  src/main/target/MICOAIR405V2/config.c
  src/main/target/MICOAIR405V2/target.c
  src/main/target/MICOAIR405V2/target.h
  src/main/target/MICOAIR743/CMakeLists.txt
  src/main/target/MICOAIR743/config.c
  src/main/target/MICOAIR743/target.c
  src/main/target/MICOAIR743/target.h
Labels: New target

#10122 Add a new target KakuteF4wing
  src/main/target/KAKUTEF4WING/CMakeLists.txt
  src/main/target/KAKUTEF4WING/config.c
  src/main/target/KAKUTEF4WING/hardware_setup.c
  src/main/target/KAKUTEF4WING/target.c
  src/main/target/KAKUTEF4WING/target.h
Labels: New target

#10169 SBUS2 telemetry support
  docs/SBUS2_Telemetry.md
  docs/Telemetry.md
  src/main/CMakeLists.txt
  src/main/build/debug.h
  src/main/common/maths.h
  src/main/fc/cli.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/sbus.h
  src/main/scheduler/scheduler.h
  src/main/target/common.h
  src/main/telemetry/sbus2.c
  src/main/telemetry/sbus2.h
  src/main/telemetry/sbus2_sensors.c
  src/main/telemetry/sbus2_sensors.h
  src/main/telemetry/telemetry.c
Labels: Ready to merge
