Repository iNavFlight/inav, pull requests merged in 2024-01, with the labels that each got.

#9609 Fix ahi pitch when inverted
  src/main/io/osd_canvas.c
  src/main/io/osd_common.c
Labels: Ready to merge

#9630 Add support for SKYSTARSF722HDPRO
  src/main/target/SKYSTARSF722HD/CMakeLists.txt
  src/main/target/SKYSTARSF722HD/target.h
Labels: Don't merge

#9675 Change LPF filter setting for accgyro_icm42605.c and enable/configure hardware AA filter
  src/main/drivers/accgyro/accgyro_icm42605.c
Labels: Testing Required
