Repository iNavFlight/inav, pull requests merged in 2024-06, with the labels that each got.

#10070 Add JHEF405PRO (aka GHF405AIO-HD) support
  src/main/target/JHEF405PRO/CMakeLists.txt
  src/main/target/JHEF405PRO/target.c
  src/main/target/JHEF405PRO/target.h
Labels: Unofficial Target, New target

#10100 Add battery profile to programming framework
  src/main/programming/logic_condition.c
  src/main/programming/logic_condition.h
Labels: Requires Configurator

#10102 Consolidate the old `PIDProfile` and `Profile` in to `Control Profile`
  docs/Control Profiles.md
  docs/Programming Framework.md
  src/main/fc/cli.c
Labels: Release Notes, Requires Configurator

#10096 Added new targets FLYWOOF722PRO, F405HD, updated F745, F405PRO config
  src/main/target/FLYWOOF405PRO/CMakeLists.txt
  src/main/target/FLYWOOF405PRO/config.c
  src/main/target/FLYWOOF405PRO/target.c
  src/main/target/FLYWOOF405PRO/target.h
  src/main/target/FLYWOOF722PRO/CMakeLists.txt
  src/main/target/FLYWOOF722PRO/config.c
  src/main/target/FLYWOOF722PRO/target.c
  src/main/target/FLYWOOF722PRO/target.h
  src/main/target/FLYWOOF745/target.c
  src/main/target/FLYWOOF745/target.h
Labels: New target, Samples Received

#9879 Adaptive gyro filter based on signal statistics experiment
  .vscode/c_cpp_properties.json
  cmake/at32.cmake
  cmake/stm32.cmake
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/build/debug.h
  src/main/fc/config.c
  src/main/fc/fc_tasks.c
  src/main/fc/settings.yaml
  src/main/flight/adaptive_filter.c
  src/main/flight/adaptive_filter.h
  src/main/flight/dynamic_lpf.c
  src/main/flight/ez_tune.c
  src/main/flight/pid.c
  src/main/scheduler/scheduler.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/SITL/target.h
  src/main/target/common.h
Labels: In progress, Experimental, Release Notes

#10109 Serial gimbal and headtracker support
  .gitignore
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/build/debug.h
  src/main/config/parameter_group_ids.h
  src/main/drivers/gimbal_common.c
  src/main/drivers/gimbal_common.h
  src/main/drivers/headtracker_common.c
  src/main/drivers/headtracker_common.h
  src/main/fc/fc_init.c
  src/main/fc/fc_msp.c
  src/main/fc/fc_msp_box.c
  src/main/fc/fc_tasks.c
  src/main/fc/rc_modes.h
  src/main/fc/settings.yaml
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/io/gimbal_serial.c
  src/main/io/gimbal_serial.h
  src/main/io/headtracker_msp.c
  src/main/io/headtracker_msp.h
  src/main/io/serial.h
  src/main/msp/msp_protocol_v2_sensor.h
  src/main/scheduler/scheduler.h
  src/main/target/SITL/target.h
  src/main/target/common.h
  src/test/unit/CMakeLists.txt
  src/test/unit/gimbal_serial_unittest.cc
  src/test/unit/maths_unittest.cc
Labels: Requires Configurator

#10166 bind_rx cli command now supports CRSF based receivers
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/msp/msp_protocol_v2_common.h
  src/main/rx/crsf.c
  src/main/rx/crsf.h
Labels: Testing Required

#9883 Fixed position for formation flight / inav radar
  docs/Settings.md
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/settings.yaml
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Requires Configurator

#10165 Allow SBUS servo protocol to output 18 channels, expand mixer to up to 24 channels
  src/main/drivers/pwm_mapping.h
  src/main/fc/rc_controls.h
  src/main/flight/servos.c
  src/main/flight/servos.h
  src/main/io/servo_sbus.c
  src/main/rx/sbus_channels.c
  src/main/rx/sbus_channels.h
Labels: Requires Configurator

#10177 Gyro LULU smoother as gyro filter alternative
  docs/Settings.md
  src/main/CMakeLists.txt
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/common/lulu.c
  src/main/common/lulu.h
  src/main/fc/config.c
  src/main/fc/settings.yaml
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Experimental
