Repository iNavFlight/inav, pull requests merged in 2025-01, with the labels that each got.

#10417 Add new target for HGLRCF405V2
  src/main/target/HGLRCF405V2/CMakeLists.txt
  src/main/target/HGLRCF405V2/target.c
  src/main/target/HGLRCF405V2/target.h
Labels: New target

#10541 Fixed wing altitude control fixes
  docs/Settings.md
  src/main/cms/cms_menu_imu.c
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/fc/settings.yaml
  src/main/flight/pid.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
  src/main/navigation/navigation.c
Labels: Release Notes, Requires Configurator

#10523 Add targets for SEQUREH7 and SEQUREH7V2
  src/main/drivers/timer_def_stm32h7xx.h
  src/main/target/SEQUREH7/CMakeLists.txt
  src/main/target/SEQUREH7/config.c
  src/main/target/SEQUREH7/target.c
  src/main/target/SEQUREH7/target.h
Labels: In progress, New target

#10598 O4 arming workaround
  docs/Settings.md
  src/main/fc/settings.yaml
  src/main/io/displayport_msp_osd.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/main/io/osd_dji_hd.c
  src/main/io/osd_dji_hd.h
Labels: Release Notes

#10594 Added extra format to Custom OSD Elements
  src/main/fc/cli.c
  src/main/fc/fc_msp.c
  src/main/io/osd/custom_elements.c
  src/main/io/osd/custom_elements.h
Labels: Requires Configurator

#10607 Remove blocking delay from batteryUpdate initialization
  src/main/sensors/battery.c
Labels: Testing Required, Don't merge

#10600 Add new target: AET-H743-Basic
  src/main/target/AETH743Basic/CMakeLists.txt
  src/main/target/AETH743Basic/config.c
  src/main/target/AETH743Basic/target.c
  src/main/target/AETH743Basic/target.h
Labels: New target

#10621 Fixed wing flight detection fix
  src/main/navigation/navigation.c
  src/main/navigation/navigation_fixedwing.c
  src/main/navigation/navigation_fw_launch.c
  src/main/navigation/navigation_private.h
Labels: Enhancement

#10557 Add new targets: MicoAir743AIO and MicoAir743v2
  src/main/target/MICOAIR743AIO/CMakeLists.txt
  src/main/target/MICOAIR743AIO/config.c
  src/main/target/MICOAIR743AIO/target.c
  src/main/target/MICOAIR743AIO/target.h
  src/main/target/MICOAIR743V2/CMakeLists.txt
  src/main/target/MICOAIR743V2/config.c
  src/main/target/MICOAIR743V2/target.c
  src/main/target/MICOAIR743V2/target.h
Labels: New target
