Repository iNavFlight/inav, pull requests merged in 2025-05, with the labels that each got.

#10694 add barometer altitude to crsf telemetry
  src/main/rx/crsf.h
  src/main/telemetry/crsf.c
Labels: Testing Required

#10571 MSP command to get radar position of other planes from esp32radar
  src/main/fc/fc_msp.c
  src/main/msp/msp_protocol_v2_common.h
Labels: New Feature

#10416 Lulu fixes and improvements
  src/main/common/lulu.c
  src/main/common/lulu.h
Labels: Ready to merge
